
[English]
Continue = 'Continue'
Go_Back = 'Go Back'
Choreo = 'Choreo'
Ready_Dance = 'Ready to Dance!'
Sort_Title = '''Sort by
title'''
Sort_Artist = '''Sort by
artist'''
Sort_Level = '''Sort by
level'''
Level = 'Level '
Sort_Score = '''Sort by
high score'''
DJ_choice = 'DJ’s choice'
Easy = 'Easy'
Normal = 'Normal'
Hard = 'Hard'
Scroll = 'Scroll'
Auto_Mode_Enabled = '''Auto Mode Enabled'''
Stylish = 'Stylish'
Cool = 'Cool'
Good = 'Good'
Miss = 'Miss'
Early = 'Early'
Late = 'Late'
Results = 'Results'
Accuracy = 'Accuracy'
Full_Combo = 'Full Combo'
Cleared = 'Cleared'
Failed = 'Failed'
Forfeit = 'Forfeit'
No_Songs_Title = 'No songs loaded'
No_Songs_Desc = 'Add song files to the folder “StyleStar/Songs”. Each song should be in its own subfolder, and contain the audio file, the song metadata (.ssi), and one or more chart files (.ssf).'
Lang_Title = 'Language'
Lang_Open = 'Open language select...'
Lang_Name = 'English'
Screen_Res = 'Screen resolution'
Touch_Res = 'Touchscreen orientation'
Hor_0 = 'Horizontal (0°)'
Ver_90 = 'Vertical (90°)'
Hor_180 = 'Horizontal (180°)'
Ver_270 = 'Vertical (270°)'
En_Free = 'Enable free play'
Auto_Mode_2 = 'Auto Mode'
On = 'On'
Off = 'Off'
Down_Only = 'DOWN only'
Save_Exit = 'Save and Exit'
Leave_No_Save = 'Leave without Saving'
Select_Confirm = 'Press SELECT again to confirm changes.'
Select_Discard = 'Press SELECT again to discard changes.'

[Spanish]
Continue = 'Continuar'
Go_Back = 'Retroceder'
Choreo = 'Coreografía'
Ready_Dance = '¡Vamos a bailar!'
Sort_Title = 'Ordenar por título'
Sort_Artist = 'Ordenar por artista'
Sort_Level = 'Ordenar por nivel'
Level = 'Nivel '
Sort_Score = 'Ordenar por highscore'
DJ_choice = 'Deja que el DJ decidir'
Easy = 'Fácil'
Normal = 'Regular'
Hard = 'Difícil'
Scroll = 'Velocidad'
Auto_Mode_Enabled = 'Modo Auto Activado'
Stylish = 'Estiloso'
Cool = 'Guay'
Good = 'Bien'
Miss = 'Fallo'
Early = 'Pronto'
Late = 'Tarde'
Results = 'Resultados'
Accuracy = 'Precisión'
Full_Combo = 'Combo Completo'
Cleared = 'Pasado'
Failed = 'Fallido'
Forfeit = 'Abandonado'
No_Songs_Title = 'No hay canciones'
No_Songs_Desc = 'Añada archivos a la carpeta "StyleStar/Songs". Cada canción debe tener su propia carpeta, y contener un archivo de audio, los metadatos (.ssi) y al menos un archivo para la partitura (.ssf).'
Lang_Title = 'Idioma'
Lang_Open = 'Abre el menú de idiomas...'
Lang_Name = 'español'
Screen_Res = 'Resolución de la pantalla'
Touch_Res = 'Orientación de la pantalla táctil'
Hor_0 = 'Horizontal (0°)'
Ver_90 = 'Vertical (90°)'
Hor_180 = 'Horizontal (180°)'
Ver_270 = 'Vertical (270°)'
En_Free = 'Activar free play'
Auto_Mode_2 = 'Modo Auto'
On = 'Activado'
Off = 'Desactivado'
Down_Only = 'Solo DOWN'
Save_Exit = 'Guardar y salir'
Leave_No_Save = 'Salir sin guardar'
Select_Confirm = 'Pulsa SELECT otra vez para confirmar los cambios.'
Select_Discard = 'Pulsa SELECT otra vez para descartar los cambios.'

[Japanese]
Continue = '次へ'
Go_Back = '戻る'
Choreo = '振付'
Ready_Dance = '準備オッケー！'
Sort_Title = '''タイトルで
並べ替え'''
Sort_Artist = '''アーティストで
並べ替え'''
Sort_Level = '''レベルで
並べ替え'''
Level = 'レベル'
Sort_Score = '''ハイスコアで
並べ替え'''
DJ_choice = 'DJにお任せ'
Easy = '簡単'
Normal = '普通'
Hard = '難しい'
Scroll = 'スクロール'
Auto_Mode_Enabled = 'オートプレイON'
Stylish = 'スタイリッシュ'
Cool = 'イケテル'
Good = 'ウマイ'
Miss = 'ミス'
Early = '早すぎ'
Late = '遅すぎ'
Results = 'ケッカ ハッピョウ'
Accuracy = '精度'
Full_Combo = 'フルコンボ'
Cleared = 'クリア'
Failed = 'クリアならず'
Forfeit = 'ギブアップ'
No_Songs_Title = 'ガッキョク データ ガ アリマセン'
No_Songs_Desc = '曲のファイルをフォルダ StyleStar¥Songs に、一曲づつサブフォルダに入れてください。一曲につき、音声ファイル1個と、楽曲メタデータファイル（.ssi）1個と、譜面ファイル（.ssf）1個以上が必要です。'
Lang_Title = '言語'
Lang_Open = '言語選択を開く...'
Lang_Name = '日本語'
Screen_Res = '画面解像度'
Touch_Res = 'タッチスクリーンの向き'
Hor_0 = '横 (0°)'
Ver_90 = '縦 (90°)'
Hor_180 = '横 (180°)'
Ver_270 = '縦 (270°)'
En_Free = 'フリープレイをオンにする'
Auto_Mode_2 = 'オートプレイ'
On = '有効'
Off = '無効'
Down_Only = 'DOWNのみ'
Save_Exit = '保存して終了'
Leave_No_Save = '保存せずに終了'
Select_Confirm = '変更を保存するには、SELECTを押してください。'
Select_Discard = '変更を破棄するには、SELECTを押してください。'

[French]
Continue = 'Continuer'
Go_Back = 'Retour'
Choreo = 'Chorégraphie'
Ready_Dance = 'Prêt à danser!'
Sort_Title = 'Trier par titre'
Sort_Artist = 'Trier par artiste'
Sort_Level = 'Trier par niveau'
Level = 'Niveau '
Sort_Score = 'Trier par score'
DJ_choice = 'Choix du DJ'
Easy = 'Facile'
Normal = 'Normal'
Hard = 'Difficile'
Scroll = 'Défilement'
Auto_Mode_Enabled = 'Mode automatique'
Stylish = 'Stylé'
Cool = 'Cool'
Good = 'Bien'
Miss = 'Raté'
Early = 'Trop tôt'
Late = 'Trop tard'
Results = 'Résultats'
Accuracy = 'Précision'
Full_Combo = 'Combo parfait'
Cleared = 'Réussi'
Failed = 'Échec'
Forfeit = 'Abandon'
No_Songs_Title = 'Aucune chanson trouvée'
No_Songs_Desc = 'Ajoute des fichiers de chansons dans le dossier "StyleStar/Songs". Chaque chanson doit se trouver dans son propre dossier, et doit contenir le fichier audio, les métadonnées (.ssi), et une ou plusieurs chorégraphies (.ssf).'
Lang_Title = 'Langue'
Lang_Open = 'Ouvre la sélection de langue...'
Lang_Name = 'français'
Screen_Res = "Résolution d'écran"
Touch_Res = "Orientation de l'écran"
Hor_0 = 'Paysage (0°)'
Ver_90 = 'Portrait (90°)'
Hor_180 = 'Paysage (180°)'
Ver_270 = 'Portrait (270°)'
En_Free = 'Activer le Free Play'
Auto_Mode_2 = 'Mode automatique'
On = 'Activé'
Off = 'Désactivé'
Down_Only = 'Seulement le DOWN'
Save_Exit = 'Enregistrer et quitter'
Leave_No_Save = 'Quitter sans enregistrer'
Select_Confirm = 'Appuyer sur SELECT à nouveau pour confirmer les changements.'
Select_Discard = 'Appuyer sur SELECT à nouveau pour ignorer les changements.'
